library(shiny) 

shinyUI(pageWithSidebar( 

  headerPanel("Planets and Moons - Solar system quiz"),
  sidebarPanel(
    
    h3('Work your answers and then press GO button down below to see your results.'),
    
    numericInput('id1', '1. How many Galilean satellites does Jupiter have?', 0, min = 0, max = 10, step = 1),

    checkboxGroupInput("id2", "2. Choose planets that have no moons.",
                   c("Pluto" = "Pluto",
                     "Mercury" = "Mercury",
                     "Mars" = "Mars",
                     "Venus" = "Venus"),
                   selected = NULL),
    
    radioButtons("id3", "3. What planet is closest to Sun?",
                 c("Phaeton" = "Phaeton",
                   "Mercury" = "Mercury",
                   "Ariel" = "Ariel",
                   "Mars" = "Mars"), 
                 selected = FALSE),

    radioButtons("id4", "4. Which celestial body has been recently demoted to dwarf planets class?",
                 c("Pluto" = "Pluto",
                   "Mercury" = "Mercury",
                   "Ariel" = "Ariel",
                   "Ceres" = "Ceres"), 
                 selected = FALSE),
    
    radioButtons("id5", "5. What is the outermost inner planet of the Solar system?",
                 c("Phaeton" = "Phaeton",
                   "Mercury" = "Mercury",
                   "Pluto" = "Pluto",
                   "Mars" = "Mars"), 
                 selected = FALSE),
    
    textInput('id6', '6. Spell the name of the largest planet in the Solar system.'),
    
    radioButtons("id7", "7. Which planet in the Solar system is the only retograde planet?",
                 c("Neptune" = "Neptune",
                   "Venus" = "Venus",
                   "Uranus" = "Uranus",
                   "Mars" = "Mars"), 
                 selected = FALSE),
    
    radioButtons("id8", "8. Which planet in the Solar system has the largest tilt?",
                 c("Phaeton" = "Phaeton",
                   "Uranus" = "Uranus",
                   "Saturn" = "Saturn",
                   "Neptune" = "Neptune"), 
                 selected = FALSE),
    
    radioButtons("id9", "9. Which Earth-size planet in the Solar system has a poisonous atmosphere?",
                 c("Titan" = "Titan",
                   "Mercury" = "Mercury",
                   "Venus" = "Venus",
                   "Jupiter" = "Jupiter"), 
                 selected = FALSE),
    
    radioButtons("id10", "10. Which planet in the Solar system is confirmed to harbour life?",
                 c("Enceladus" = "Enceladus",
                   "Europa" = "Europa",
                   "Earth" = "Earth",
                   "Mars" = "Mars"), 
                 selected = FALSE),
    
    radioButtons("id11", "11. Which planet in the Solar system has a single moon?",
                 c("Earth" = "Earth",
                   "Mercury" = "Mercury",
                   "Pluto" = "Pluto",
                   "Venus" = "Venus"), 
                 selected = FALSE),
    
    radioButtons("id12", "12. Which planet in the Solar system has exactly two moons?",
                 c("Jupiter" = "Jupiter",
                   "Neptune" = "Neptune",
                   "Venus" = "Venus",
                   "Mars" = "Mars"), 
                 selected = FALSE),
    
    radioButtons("id13", "13. What is the outer most planet of the Solar system?",
                 c("Phaeton" = "Phaeton",
                   "Neptune" = "Neptune",
                   "Pluto" = "Pluto",
                   "Mercury" = "Mercury"), 
                 selected = FALSE),
    
    radioButtons("id14", "14. Which planet in the Solar system has a distinguished set of rings?",
                 c("Jupiter" = "Jupiter",
                   "Saturn" = "Saturn",
                   "Pluto" = "Pluto",
                   "Mars" = "Mars"), 
                 selected = FALSE),
    
    radioButtons("id15", "15. Which planet in the Solar system has a moon named Titan?",
                 c("Phaeton" = "Phaeton",
                   "Mercury" = "Mercury",
                   "Saturn" = "Saturn",
                   "Mars" = "Mars"), 
                 selected = FALSE),
    
    numericInput('id16', '16. How many planets are there in the Solar system?', 0, min = 0, max = 10, step = 1),
    
    actionButton("goButton", "GO!"),
    width = 7
  ),

  mainPanel(
        h3('---------------------- '),
        h3('--- Your results: --- '),
        h3('---------------------- '),
        h5('Question 1.'),
        verbatimTextOutput("oid1"),
        verbatimTextOutput("result1"),
        h5('Question 2.'),
        verbatimTextOutput("oid2"),
        verbatimTextOutput("result2"),
        h5('Question 3.'),
        verbatimTextOutput("oid3"),
        verbatimTextOutput("result3"),
        h5('Question 4.'),
        verbatimTextOutput("oid4"),
        verbatimTextOutput("result4"),
        h5('Question 5.'),
        verbatimTextOutput("oid5"),
        verbatimTextOutput("result5"),
        h5('Question 6.'),
        verbatimTextOutput("oid6"),
        verbatimTextOutput("result6"),
        h5('Question 7.'),
        verbatimTextOutput("oid7"),
        verbatimTextOutput("result7"),
        h5('Question 8.'),
        verbatimTextOutput("oid8"),
        verbatimTextOutput("result8"),
        h5('Question 9.'),
        verbatimTextOutput("oid9"),
        verbatimTextOutput("result9"),
        h5('Question 10.'),
        verbatimTextOutput("oid10"),
        verbatimTextOutput("result10"),
        h5('Question 11.'),
        verbatimTextOutput("oid11"),
        verbatimTextOutput("result11"),
        h5('Question 12.'),
        verbatimTextOutput("oid12"),
        verbatimTextOutput("result12"),
        h5('Question 13.'),
        verbatimTextOutput("oid13"),
        verbatimTextOutput("result13"),
        h5('Question 14.'),
        verbatimTextOutput("oid14"),
        verbatimTextOutput("result14"),
        h5('Question 15.'),
        verbatimTextOutput("oid15"),
        verbatimTextOutput("result15"),
        h5('Question 16.'),
        verbatimTextOutput("oid16"),
        verbatimTextOutput("result16"),
        width = 5
  )
))
